spring:
  application:
    name: SalaryManagementSystem
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/salarymanagementsystem?serverTimezone=GMT%2B8
    username: root
    password: 123233


server:
  port: 8000